/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "uphjuoufadwafjiraelb"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwaGp1b3VmYWR3YWZqaXJhZWxiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4NDA0MTgsImV4cCI6MjA3NDQxNjQxOH0.Rkfqqub6UcIZWngej2KL-1H-UbuwRsCAziUbU9a_bTk"